Traceback (most recent call last):
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\hp\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.decomposition import TruncatedSVD
lsa_model = TruncatedSVD(n_components=50, algorithm='randomized', n_iter=10, random_state=42)

lsa_top=lsa_model.fit_transform(vect_text)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_10868/3090274223.py[0m in [0;36m<module>[1;34m[0m
[0;32m      2[0m [0mlsa_model[0m [1;33m=[0m [0mTruncatedSVD[0m[1;33m([0m[0mn_components[0m[1;33m=[0m[1;36m50[0m[1;33m,[0m [0malgorithm[0m[1;33m=[0m[1;34m'randomized'[0m[1;33m,[0m [0mn_iter[0m[1;33m=[0m[1;36m10[0m[1;33m,[0m [0mrandom_state[0m[1;33m=[0m[1;36m42[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [1;33m[0m[0m
[1;32m----> 4[1;33m [0mlsa_top[0m[1;33m=[0m[0mlsa_model[0m[1;33m.[0m[0mfit_transform[0m[1;33m([0m[0mvect_text[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mNameError[0m: name 'vect_text' is not defined
NameError: name 'vect_text' is not defined

